### ISSUE TITLE
Hardware Specification

### ISSUE THREAD

**Issue by solnou** [Esc-IngComp-UNC/staff-access-monitoring-system#1]
Define and document the hardware components required for the staff access monitoring system. This includes selecting the appropriate fingerprint sensor, ESP32 model, power supply, RTC module and any other necessary peripherals.

**Comment by valentinrb1** [comment]
You would need to add a hardware component to obtain the real time that allows you to record the entry and exit times.
#6

**Comment by GabrielEValenzuela** [comment]
Is this task part of an epic? 

Don't forget to add all issues to the project! ❤️

**Comment by solnou** [comment]
Micro-controller: ESP32 devkit v1
Fingerprint sensor: R305
Display LCD: 16x2 I2C

**Comment by solnou** [comment]
Micro-controller: ESP32 devkit v1
Fingerprint sensor: R305
Display LCD: 16x2 I2C

**Comment by francobottini99** [comment]
Issue #2 is contained herein. It is closed.

**Comment by francobottini99** [comment]
The proposed hardware does not support the Ethernet interface. Also check if it is necessary to add hardware to differentiate between inputs and outputs (e.g. a button that, if pressed before placing the finger on it, is considered an output, otherwise, it is considered an input).

**Comment by GabrielEValenzuela** [comment]
Hi team! 

Please make sure to upload any documentation related to the devices we're using in our project (e.g., manuals, datasheets, user guides). This will help everyone stay informed and ensure we have all the necessary resources at our disposal ❤️
