### ISSUE TITLE
Hardware Prototyping

### ISSUE THREAD

**Issue by solnou** [Esc-IngComp-UNC/staff-access-monitoring-system#10]
This issue addresses the creation of an initial hardware prototype. The following steps have been identified as part of this implementation:
- Hardware Setup on a Protoboard: The hardware components must be assembled on a protoboard for the use on the proeject.
- Software Integration: A foundational software layer has to be developed to interface with the hardware, enabling data capture from the setup.

Tasks:
- Validate the hardware setup and ensure stability on the protoboard.
- Test the data capture functionality to verify the accuracy and consistency of the information collected.
- Document any issues or limitations observed during the testing phase.

**Comment by solnou** [comment]
28/10/2024 We established an initial connection prototype between the ESP32 and the fingerprint sensor to familiarize ourselves with the hardware. We verified the correct functionality of the sensor by capturing a few test fingerprints.

Spent 🍅 6+

**Comment by GabrielEValenzuela** [comment]
Is this task done?

**Comment by solnou** [comment]
05/12/2024 A prototype was built by connecting the main components. Some components were excluded due to budget and time issues. Only those essential for operation were included. Basic operational tests were performed, connecting the ESP32 and loading simple codes to verify that we could communicate with each component using known libraries.

We consider the task complete

Spent 🍅 5+

**Comment by GabrielEValenzuela** [comment]
Perfect, let's close it and move on!
