### ISSUE TITLE
Hardware schematics

### ISSUE THREAD

**Issue by Jorgear27** [Esc-IngComp-UNC/staff-access-monitoring-system#2]
Design and create the hardware schematics for the system, showing the connections between the ESP32, fingerprint sensor, power supply, I2C LED screen RTC module.

**Comment by solnou** [comment]
Pin TD (pin 3) del R305 al pin RXD del ESP32 (GPIO16- Pin 25)
Pin RD (pin 4) del R305 al pin TXD del ESP32 (GPIO17- Pin 27)
Pin SDA (pin 3) del I2C LCD al pin GPIO21 del ESP32 
Pin SCL (pin 4) del I2C LCD al pin GPIO22 del ESP32

**Comment by GabrielEValenzuela** [comment]
We need a little improvement on this task

First, we need to define the purpose of this task and whether it is a research task, including any source of graphics to the documentary the result of the research ❤️

**Comment by francobottini99** [comment]
It is dealt with in #1.
