### ISSUE TITLE
Research Back-End Technologies

### ISSUE THREAD

**Issue by Jorgear27** [Esc-IngComp-UNC/staff-access-monitoring-system#5]
Research and evaluate different back-end technologies that can be used to support the staff access monitoring system. This includes selecting the appropriate server framework, database system and any other tools taken into consideration.

**Comment by valentinrb1** [comment]
The objective of a research is not to show the tool that has been chosen, but to look for different types of tools to make a comparison between them, name advantages and disadvantages and then make a choice.

In addition, we provide a basic scheme of the interconnection that the Back-End has so that you can better orient yourself and make comparisons of the tools that can be used.

![PPS_ARCHITECTURE](https://github.com/user-attachments/assets/bfaf2117-46ae-4711-9e33-cf97b694fc02)

> [!NOTE]
> The tools that we provide in the image are illustrative, you can compare the ones you want.

**Comment by GabrielEValenzuela** [comment]
I think we should consider Go for the backend, it's a compiled language with a low learning curve.

You can use it with https://gofiber.io/

**Comment by Jorgear27** [comment]
# Back-End Technology Research

## 1. Introduction

The purpose of this research is to evaluate and compare various back-end technologies that could be used to support the staff access monitoring system. The system requires secure storage of data, user identity management, and real-time access monitoring through a web interface. This research focuses on server frameworks, database systems, and communication protocols.

The Back-End is crucial for the correct development of the staff access monitoring system. As shown in the requirements, the back end must be responsible for the data processing and implementing the logic of the system. It also needs to centralize the data management and provide a secure environment for the communication between the ESP32 and the database. 

Given the requirements specified in the Epics SRS, we will evaluate different technologies that can fulfill the needs of the project.

## 2. Back-End Server Frameworks

### 2.1. Go (Golang)
Go is a statically typed, compiled language designed for high performance and concurrency. It is well-suited for back-end development due to its simplicity and efficiency. Go’s standard library includes a robust HTTP server (`net/http`), making it an excellent choice for building RESTful APIs or handling HTTP communication.

#### Advantages:
- **Performance**: Go’s compiled nature offers significant performance benefits, especially for a system with multiple and simultaneous requests. 
- **Concurrency**: A key feature of Go is its lightweight goroutines, which allow efficient multitasking without the overhead of traditional threading models. 
- **Cross-Platform Compilation**: Go is cross-platform, which makes it easier to deploy across different environments (e.g., Linux servers, Windows, or macOS).
- **Security**: Go has built-in support for various cryptography libraries and secure communication protocols (e.g., HTTPS), which can help in ensuring that sensible data is securely transmitted and stored.

#### Disadvantages:
- **Young Ecosystem**: While growing, Go's ecosystem is not as extensive as older languages like Python or Java.

### 2.2. Node.js
Node.js is a JavaScript runtime built on Chrome's V8 engine, allowing developers to write server-side code in JavaScript. It is non-blocking and asynchronous by nature, making it ideal for handling I/O-heavy tasks such as web servers or real-time applications.

#### Advantages:
- **Non-blocking I/O**: Node.js is event-driven and non-blocking, which makes it highly efficient for real-time applications like our access monitoring.
- **Fast Development Cycle**: JavaScript is widely known, so development and prototyping can be faster.
- **Large Ecosystem**: NPM (Node Package Manager) offers a vast number of libraries and tools.

#### Disadvantages:
- **Single-threaded**: Although non-blocking, Node.js runs on a single thread, which can pose performance limitations under heavy computational load.
- **Performance**: Not as fast as compiled languages like Go or C++ for CPU-intensive tasks.

### 2.3. Django (Python)
Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design.

#### Advantages:
- **Simple Use**: Python’s syntax is readable and easy to learn, and Django is well-documented.
- Comes with many built-in tools, such as an admin interface, authentication, and database management.
- **Large Community**: A vast community for support and extensive third-party plugins.

#### Disadvantages:
- **Performance**: Python, being an interpreted language, is slower than Go or Node.js.
- **Scalability**: While scalable, Django may not be our best choice for large-scale real-time systems due to its slower performance compared to languages like Go.

### 2.4. Spring Boot (Java)
Spring Boot is a framework for building microservices in Java, widely used for enterprise-level applications.

#### Advantages:
- **Robustness**: Java is a mature language with strong type safety and extensive libraries for any type of applications.
- **Performance**: Compiled and fast, with a focus on scalability and reliability.
- **Enterprise Features**: Well-suited for complex, large-scale applications requiring high reliability.

#### Disadvantages
- **Complexity**: Java and Spring Boot can be complex and require more setup compared to Go or Django.
- **Memory Usage**: Java applications tend to have higher memory overhead.

### 2.5. C#
C# is a mature, object-oriented language used for enterprise-level applications, typically in combination with the .NET framework. It is highly versatile and can be used to build web APIs and desktop applications.

#### Advantages
- **Enterprise-Ready**: C# offers a rich set of libraries and tools for building enterprise-level applications with security, scalability, and reliability.
- **Strong Community**: The .NET community is vast and provides extensive support for building robust applications.

#### Disadvantages
-  The learning curve for .NET might be higher compared to Go or Node.js, and C# applications can be more resource-intensive.

### 2.6. Rust
Rust is a systems programming language focused on safety and performance, known for its memory safety and low-level control. Although relatively new to web development, frameworks like Actix Web and Rocket make Rust an attractive option for high-performance back-end servers.
#### Advantages
- **Performance**: Rust offers superior performance for CPU-bound tasks, making it ideal for systems where efficiency and memory management are critical.
- **Safety**: Rust guarantees memory safety, reducing the risk of bugs related to concurrent programming.

#### Disadvantages
- While performant, Rust’s steeper learning curve and lower-level control may increase development time compared to Go or Node.js.

#### **Discussion:**
- **Go vs. Node.js**: Go’s compiled nature and concurrency model make it more efficient than Node.js for CPU-bound tasks. Node.js, on the other hand, is excellent for rapid prototyping and real-time I/O tasks but might struggle with data processing at scale.
- **Go vs. C#**: C# provides a mature ecosystem with enterprise-level tools, but Go’s simplicity and focus on modern web back-end development make it easier to learn and quicker to develop with.
- **Go vs. Rust**: Rust offers excellent performance and memory safety, but its steeper learning curve and longer development time may be a disadvantage compared to Go, which is designed for simplicity and fast development.

In early conclusion, Go offers the right balance of simplicity, performance, and concurrency for our back-end, making it a strong choice for both real-time access monitoring and more traditional web-based administration tasks (over HTTP). The communication protocols and back-end framework together provide a robust and scalable system.

## 3. Databases

### 3.1. PostgreSQL
PostgreSQL is an open-source relational database known for its standards compliance and robustness.
#### Advantages:
- **ACID Compliance**: Ensures high data integrity and security.
- **Extensibility**: Supports custom functions and complex queries.
- **Security Features**: Offers strong data encryption and access control.
#### Disadvantages:
- **Setup Complexity**: More difficult to set up and configure compared to simpler alternatives like SQLite.

### 3.2. MySQL
MySQL is a popular relational database management system (RDBMS) that uses SQL (Structured Query Language) for querying and managing data. It is widely adopted and suited for applications requiring structured data storage with relationships between tables.
#### Advantages:
- ACID compliance ensures reliable transactions, and MySQL’s indexing and query optimization provide fast access to data.
- MySQL would be well-suited for storing structured access logs and staff data where relationships between tables (e.g., user profiles and log entries) can be required.
#### Disadvantages:
- **Limitations**: Scaling MySQL horizontally across many servers can be challenging.

### 3.3. MongoDB
MongoDB is a NoSQL database that stores data in flexible, JSON-like documents rather than traditional rows and columns. This schema-less approach allows for greater flexibility in handling unstructured or semi-structured data.
#### Advantages:
- MongoDB is ideal for handling large volumes of data with a flexible schema, which is useful for scenarios where the data format might change over time.
- **Scalability**: MongoDB offers excellent horizontal scalability, making it a strong choice if the system needs to scale quickly.
#### Disaantages:
- Unlike relational databases, MongoDB lacks ACID compliance in distributed transactions and lacks strong support for specialized queries and joins.

### 3.4. ScyllaDB
ScyllaDB is a NoSQL database and offers high throughput and low-latency operations, making it an excellent choice for high-performance, real-time applications.
#### Advantages:
- ScyllaDB boasts extreme scalability and can handle massive amounts of data, with high throughput and low latency. This is ideal for systems that may grow quickly and require fast, reliable access to logs.
- **Efficiency**: ScyllaDB is written in C++, which allows it to outperform databases written in Java, making it more efficient at utilizing hardware resources.
- ScyllaDB could be beneficial for handling the storage of time-series data, such as our access logs that are continuously updated in real-time.
#### Disadvantages:
- Like other NoSQL databases, ScyllaDB lacks strong support for complex queries and joins, which could limit its use if relational data models are required.

#### **Discussion:**
We believe, MongoDB stands out as one of the best database option for the staff access monitoring system due to its flexibility and ability to handle diverse data formats. MongoDB's horizontal scalability ensures that as the system grows and data volume increases, it can scale efficiently, providing fast access and easy management. Its flexibility, combined with strong community support and integration with modern back-end frameworks like Go, makes MongoDB an ideal choice for this project.

## 4. Communication Protocols

### 4.1. HTTP (HyperText Transfer Protocol)
HTTP is a widely used protocol for communication between clients and servers on the web.

#### Advantages:
- **Simplicity**: HTTP is straightforward to implement and widely supported by web frameworks, including Go’s `net/http` library.
- **Compatibility**: It is compatible with most web browsers and front-end tools.
- **Security**: With HTTPS, we can easily ensure secure communication between the front-end, station, and back-end.
- **Statelessness**: HTTP is ideal for managing discrete user actions, such as accessing and logging staff records.

#### Disadvantages:
- **Latency**: While suitable for most use cases, HTTP may introduce slight latency in scenarios requiring real-time updates, though it should be negligible for our staff access system.
- **Overhead**: HTTP can involve a bit more data transfer overhead compared to more lightweight protocols like MQTT, but this also shouldn't be a significant issue for our type of system.

### 4.2. MQTT (Message Queuing Telemetry Transport)
MQTT is a lightweight messaging protocol commonly used in IoT (Internet of Things) applications for real-time communication.

#### Advantages:
- **Lightweight**: Designed for minimal bandwidth consumption, making it ideal for environments with limited network capacity.
- **Real-Time Communication**: MQTT supports persistent connections and facilitates real-time communication, perfect for monitoring scenarios where instant updates are required.
- **Scalability**: Efficient for scenarios where devices continuously send data.

#### Disadvantages:
- **Security**: While it supports encryption, MQTT often requires additional configuration for secure communication (e.g., with SSL/TLS).
- **Complexity**: More complex to implement and configure compared to HTTP, especially in the context of authentication.

#### **Discussion**:
HTTP is a reliable choice for the back-end communication of the staff access monitoring system. It ensures straightforward implementation and integration with both the front-end and station devices, while providing the necessary security features.
