### ISSUE TITLE
Research Software Architecture

### ISSUE THREAD

**Issue by francobottini99** [Esc-IngComp-UNC/staff-access-monitoring-system#7]
Detailed research is required on Software Architecture. The goal is to understand the different types of architectures, their benefits and limitations, and how to apply them in software projects.

Research objectives:

- Define what software architecture is and its importance in application development.
- Explore the most common types of architectures, such as monolithic, microservices, event-driven, layer-based, among others.
- Research the advantages and disadvantages of each type of architecture, including appropriate usage scenarios.
- Analyze architectural design patterns such as MVC, MVVM, CQRS, and their role within a software architecture.
- Research tools and best practices for architecture documentation.

**Comment by solnou** [comment]
27/09 We begin the research and writing of the document

**Comment by solnou** [comment]
27/09 We begin the research and writing of the document

Spent on the day 🍅 : 3

**Comment by solnou** [comment]
27/09 We begin the research and writing of the document

Spent on the day 🍅 : 3

  &emsp;&emsp; [Document in progress](https://docs.google.com/document/d/19cJ5FGErFCq_VRUfeA9uvbMjIYaNZeQfhdEwlKDRjyw/edit?usp=sharing)

**Comment by solnou** [comment]
12/10 Document finish
Spent on the day 🍅 : 4
[Research](https://docs.google.com/document/d/19cJ5FGErFCq_VRUfeA9uvbMjIYaNZeQfhdEwlKDRjyw/edit?usp=sharing)
